### PR TITLE
Adding to npm registry

### PR DESCRIPTION
**Pull request by Halceyon**

### CODE REVIEW

**Comment by menosprezzi** [comment]
Hello @Halceyon. Nice you've contributed with our project, thanks!
We planned to publish Walkthrough to NPM registry when *v2* development is ready.
We will test your request and merge if thats all okay with!
Thanks again.

**Comment by oliveirafilipe** [comment]
@Halceyon Thank you so much for your contribution, hope you stay tune and keep helping us to make this together

**Comment by menosprezzi** [comment]
Hello @Halceyon, can you transfer the registry to our account? Because we cant publish the official package with it own name. We're starting with our organization and we plan to spread its name. Right after this transition, we will put you as a official collaborator at registry.
Thanks!

**Comment by Halceyon** [comment]
Hi,

Sure, I think the easiest is if I add you as a collaborator.  I tried adding essetwide, but there was no user found on npmjs.com.  What username should I be using?

**Pull request merged**
